site_name: Autonomi Documentation
docs_dir: docs/online-documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
  - Core Concepts:
    - Data Types: guides/data_types.md
    - Client Modes: guides/client_modes.md
    - Data Storage: guides/data_storage.md
  - Developer Guides:
    - Local Network Setup: guides/local_network.md
    - Local Development: guides/local_development.md
    - EVM Integration: guides/evm_integration.md
    - Testing Guide: guides/testing_guide.md
    - Payments: guides/payments.md
  - API Reference:
    - Overview: api/index.md
    - Client API:
      - Overview: api/autonomi-client/README.md
      - Data Types: api/autonomi-client/data_types.md
      - Error Handling: api/autonomi-client/errors.md
    - Node API:
      - Overview: api/ant-node/README.md
      - Node Configuration: api/ant-node/configuration.md
      - Network Operations: api/ant-node/network.md
    - Cryptography:
      - BLS Threshold Crypto: api/blsttc/README.md
      - Self Encryption: api/self-encryption/README.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 